document.addEventListener('DOMContentLoaded', () => {
    // --- BASE DE DATOS SIMULADA MASIVA Y 100% ÚNICA ---
    const tableData = {
        "Masculino": {
            "Mayores": {
                "A":{teams:[{pos:1,name:"SAG Villa Ballester",pts:40},{pos:2,name:"UNLu",pts:38},{pos:3,name:"Colegio Ward",pts:35},{pos:4,name:"River Plate",pts:32},{pos:5,name:"SEDALO",pts:29},{pos:6,name:"Dorrego Handball",pts:25},{pos:7,name:"Quilmes A.C.",pts:22},{pos:8,name:"Vicente López (VILO)",pts:20}],scorers:[{pos:1,name:"Diego Simonet",goals:125},{pos:2,name:"Federico Pizarro",goals:121},{pos:3,name:"Ignacio Pizarro",goals:118},{pos:4,name:"Pablo Simonet",goals:115},{pos:5,name:"Ramiro Martínez",goals:112},{pos:6,name:"Federico Fernández",goals:109},{pos:7,name:"Lucas Moscariello",goals:105},{pos:8,name:"Gastón Mouriño",goals:101},{pos:9,name:"Pablo Vainstein",goals:98},{pos:10,name:"Leonel Maciel",goals:95},{pos:11,name:"Nicolás Bonanno",goals:92},{pos:12,name:"Gonzalo Carou",goals:89},{pos:13,name:"Sebastián Simonet",goals:86},{pos:14,name:"Pedro Martínez Camí",goals:83},{pos:15,name:"Guillermo Fischer",goals:80},{pos:16,name:"Andrés Moyano",goals:77},{pos:17,name:"Juan Bar",goals:74},{pos:18,name:"Santiago Baronetto",goals:71},{pos:19,name:"Manuel Crivelli",goals:68},{pos:20,name:"Facundo Cangiani",goals:65}]},
                "B":{teams:[{pos:1,name:"Ferro Carril Oeste",pts:42},{pos:2,name:"Argentinos Juniors",pts:39},{pos:3,name:"Lomas de Zamora",pts:36},{pos:4,name:"Estudiantes de La Plata",pts:34},{pos:5,name:"Comunicaciones",pts:31},{pos:6,name:"San Lorenzo",pts:28},{pos:7,name:"Platense",pts:24},{pos:8,name:"Defensa y Justicia",pts:21}],scorers:[{pos:1,name:"Julián Souto Cueto",goals:128},{pos:2,name:"Mariano Cánepa",goals:124},{pos:3,name:"Juan Pablo Fernández",goals:120},{pos:4,name:"Sergio Crevatin",goals:117},{pos:5,name:"Damián Migueles",goals:113},{pos:6,name:"Eric Gull",goals:110},{pos:7,name:"Fernando García",goals:106},{pos:8,name:"Andrés Kogovsek",goals:102},{pos:9,name:"Matías Schulz",goals:99},{pos:10,name:"Leonardo Querín",goals:96},{pos:11,name:"Pablo Portela",goals:93},{pos:12,name:"Federico Vieyra",goals:90},{pos:13,name:"Gonzalo Carró Castro",goals:87},{pos:14,name:"James Parker",goals:84},{pos:15,name:"Martín Jung",goals:81},{pos:16,name:"Lucas Aizen",goals:78},{pos:17,name:"Francisco Lombardi",goals:75},{pos:18,name:"Fabrizio Casanova",goals:72},{pos:19,name:"Lautaro Robledo",goals:69},{pos:20,name:"Agustín Forlino Couly",goals:66}]},
                "C":{teams:[{pos:1,name:"Club Almirante Brown",pts:38},{pos:2,name:"Deportivo Morón",pts:36},{pos:3,name:"Club Atlético Atlanta",pts:34},{pos:4,name:"Villa Dálmine",pts:32},{pos:5,name:"UAI Urquiza",pts:30},{pos:6,name:"Fénix",pts:28},{pos:7,name:"Sacachispas",pts:26},{pos:8,name:"Talleres (RE)",pts:24}],scorers:[{pos:1,name:"Carlos Navarro",goals:118},{pos:2,name:"Javier Díaz",goals:115},{pos:3,name:"Daniel Gómez",goals:112},{pos:4,name:"Manuel Pérez",goals:109},{pos:5,name:"Adrián Torres",goals:106},{pos:6,name:"Marcos Rubio",goals:103},{pos:7,name:"César Castro",goals:100},{pos:8,name:"Jorge Alonso",goals:97},{pos:9,name:"Iván Romero",goals:94},{pos:10,name:"Óscar Soto",goals:91},{pos:11,name:"Félix Herrera",goals:88},{pos:12,name:"Raúl Morales",goals:85},{pos:13,name:"Esteban Vargas",goals:82},{pos:14,name:"Gabriel Reyes",goals:79},{pos:15,name:"Hugo Mendoza",goals:76},{pos:16,name:"Ricardo Castillo",goals:73},{pos:17,name:"Samuel Ortega",goals:70},{pos:18,name:"Tomás Núñez",goals:67},{pos:19,name:"Víctor Medina",goals:64},{pos:20,name:"Walter Ríos",goals:61}]},
                "D":{teams:[{pos:1,name:"Ituzaingó",pts:41},{pos:2,name:"Dock Sud",pts:39},{pos:3,name:"Laferrere",pts:37},{pos:4,name:"Excursionistas",pts:35},{pos:5,name:"Berazategui",pts:33},{pos:6,name:"Cañuelas",pts:31},{pos:7,name:"Midland",pts:29},{pos:8,name:"Luján",pts:27}],scorers:[{pos:1,name:"Agustín Vega",goals:121},{pos:2,name:"Benjamín Giménez",goals:118},{pos:3,name:"Cristian Molina",goals:115},{pos:4,name:"Dante Silva",goals:112},{pos:5,name:"Elías Cabrera",goals:109},{pos:6,name:"Facundo Juárez",goals:106},{pos:7,name:"Gastón Ibáñez",goals:103},{pos:8,name:"Hernán Rojas",goals:100},{pos:9,name:"Ignacio Domínguez",goals:97},{pos:10,name:"Joaquín Paredes",goals:94},{pos:11,name:"Kevin Ayala",goals:91},{pos:12,name:"Lautaro Acosta",goals:88},{pos:13,name:"Mateo Benítez",goals:85},{pos:14,name:"Nahuel Otero",goals:82},{pos:15,name:"Pedro Campos",goals:79},{pos:16,name:"Ramiro Chávez",goals:76},{pos:17,name:"Santino Rivas",goals:73},{pos:18,name:"Thiago Ponce",goals:70},{pos:19,name:"Ulises Ferreyra",goals:67},{pos:20,name:"Valentín Cruz",goals:64}]},
                "E1":{teams:[{pos:1,name:"Argentino de Quilmes",pts:37},{pos:2,name:"Colegiales",pts:35},{pos:3,name:"San Martín de Burzaco",pts:33},{pos:4,name:"Deportivo Armenio",pts:31},{pos:5,name:"Flandria",pts:29},{pos:6,name:"Acassuso",pts:27},{pos:7,name:"Tristán Suárez",pts:25},{pos:8,name:"Villa San Carlos",pts:23}],scorers:[{pos:1,name:"Aaron Espinoza",goals:117},{pos:2,name:"Bautista Gallardo",goals:114},{pos:3,name:"Camilo Vargas",goals:111},{pos:4,name:"Dylan Herrera",goals:108},{pos:5,name:"Enzo Castillo",goals:105},{pos:6,name:"Felipe Mendoza",goals:102},{pos:7,name:"Gael Ortega",goals:99},{pos:8,name:"Hugo Núñez",goals:96},{pos:9,name:"Ian Medina",goals:93},{pos:10,name:"Julián Ríos",goals:90},{pos:11,name:"Lisandro Flores",goals:87},{pos:12,name:"Máximo Guzmán",goals:84},{pos:13,name:"Milo Rojas",goals:81},{pos:14,name:"Noah Torres",goals:78},{pos:15,name:"Oliver Cabrera",goals:75},{pos:16,name:"Renato Paredes",goals:72},{pos:17,name:"Silas Domínguez",goals:69},{pos:18,name:"Tadeo Otero",goals:66},{pos:19,name:"Vito Benítez",goals:63},{pos:20,name:"Yago Acosta",goals:60}]},
                "E2":{teams:[{pos:1,name:"Defensores Unidos",pts:43},{pos:2,name:"Justo José de Urquiza",pts:41},{pos:3,name:"Central Córdoba (R)",pts:39},{pos:4,name:"Sportivo Italiano",pts:37},{pos:5,name:"Atlas",pts:35},{pos:6,name:"Yupanqui",pts:33},{pos:7,name:"Liniers",pts:31},{pos:8,name:"Claypole",pts:29}],scorers:[{pos:1,name:"Alejo Vidal",goals:123},{pos:2,name:"Bruno Valdéz",goals:120},{pos:3,name:"Ciro Zambrano",goals:117},{pos:4,name:"Dionisio Ramos",goals:114},{pos:5,name:"Ezequiel Figueroa",goals:111},{pos:6,name:"Fermín Salazar",goals:108},{pos:7,name:"Gerónimo Cuesta",goals:105},{pos:8,name:"Homero Montes",goals:102},{pos:9,name:"Ismael Bravo",goals:99},{pos:10,name:"Jeremías Guerrero",goals:96},{pos:11,name:"Lino Navarro",goals:93},{pos:12,name:"MATEO Páez",goals:90},{pos:13,name:"Nilo Soto",goals:87},{pos:14,name:"Octavio Delgado",goals:84},{pos:15,name:"Pascual Casco",goals:81},{pos:16,name:"Rocco Godoy",goals:78},{pos:17,name:"Segundo Sosa",goals:75},{pos:18,name:"Teo Villalba",goals:72},{pos:19,name:"Uriel Morel",goals:69},{pos:20,name:"Valerio Ávalos",goals:66}]}
            },
            "Juniors": {
                "A":{teams:[{pos:1,name:"Juniors Club A",pts:30},{pos:2,name:"Progreso Juniors",pts:28},{pos:3,name:"Unión Juvenil A",pts:25},{pos:4,name:"Los Andes Jr",pts:22},{pos:5,name:"Atenas Juniors",pts:19},{pos:6,name:"Belgrano Jr",pts:15},{pos:7,name:"Racing de Córdoba Jr",pts:12},{pos:8,name:"Instituto Jr",pts:10}],scorers:[{pos:1,name:"Alan Funes",goals:95},{pos:2,name:"Brian Heredia",goals:91},{pos:3,name:"Cristian Ledesma",goals:88},{pos:4,name:"Darío Nieva",goals:85},{pos:5,name:"Emanuel Ojeda",goals:82},{pos:6,name:"Fernando Rojas Jr",goals:79},{pos:7,name:"Gustavo Páez",goals:75},{pos:8,name:"Horacio Pereyra",goals:71},{pos:9,name:"Ismael Quiroga",goals:68},{pos:10,name:"Jonathan Santana",goals:65},{pos:11,name:"Kevin Villalba Jr",goals:62},{pos:12,name:"Lucas Godoy Jr",goals:59},{pos:13,name:"Maximiliano Correa",goals:56},{pos:14,name:"Nicolás Aguirre Jr",goals:53},{pos:15,name:"Omar Miranda",goals:50},{pos:16,name:"Patricio Franco",goals:47},{pos:17,name:"Rodrigo Molina Jr",goals:44},{pos:18,name:"Sergio Romero Jr",goals:41},{pos:19,name:"Tomás Guzmán Jr",goals:38},{pos:20,name:"Víctor Aguilera",goals:35}]},
                "B":{teams:[{pos:1,name:"Juniors Club B",pts:32},{pos:2,name:"Progreso Juniors B",pts:29},{pos:3,name:"Unión Juvenil B",pts:26},{pos:4,name:"Los Andes Jr B",pts:24},{pos:5,name:"Atenas Juniors B",pts:21},{pos:6,name:"Belgrano Jr B",pts:18},{pos:7,name:"Racing de Córdoba Jr B",pts:14},{pos:8,name:"Instituto Jr B",pts:11}],scorers:[{pos:1,name:"Abel Pintos",goals:98},{pos:2,name:"Benito Casas",goals:94},{pos:3,name:"Camilo Nieves",goals:90},{pos:4,name:"Diego Luna",goals:87},{pos:5,name:"Esteban Solari",goals:83},{pos:6,name:"Fabio Castro",goals:80},{pos:7,name:"Gabriel Mercado",goals:76},{pos:8,name:"Hernán Toledo",goals:72},{pos:9,name:"Iván Marcone",goals:69},{pos:10,name:"Javier Pinola",goals:66},{pos:11,name:"Kilian Perez",goals:63},{pos:12,name:"Leonel Vangioni",goals:60},{pos:13,name:"Marcelo Barovero",goals:57},{pos:14,name:"Neri Cardozo",goals:54},{pos:15,name:"Oscar Ustari",goals:51},{pos:16,name:"Pablo Aimar",goals:48},{pos:17,name:"Ricardo Centurión",goals:45},{pos:18,name:"Santiago Silva",goals:42},{pos:19,name:"Teófilo Gutiérrez",goals:39},{pos:20,name:"Walter Kannemann",goals:36}]},
                "C":{teams:[{pos:1,name:"Juniors Club C",pts:28},{pos:2,name:"Progreso Juniors C",pts:26},{pos:3,name:"Unión Juvenil C",pts:24},{pos:4,name:"Los Andes Jr C",pts:22},{pos:5,name:"Atenas Juniors C",pts:20},{pos:6,name:"Belgrano Jr C",pts:18},{pos:7,name:"Racing de Córdoba Jr C",pts:16},{pos:8,name:"Instituto Jr C",pts:14}],scorers:[{pos:1,name:"Ángel Di María",goals:88},{pos:2,name:"Bruno Zuculini",goals:85},{pos:3,name:"Carlos Tevez",goals:82},{pos:4,name:"Darío Benedetto",goals:79},{pos:5,name:"Eduardo Salvio",goals:76},{pos:6,name:"Franco Armani",goals:73},{pos:7,name:"Gonzalo Higuaín",goals:70},{pos:8,name:"Hernán Crespo",goals:67},{pos:9,name:"Javier Mascherano",goals:64},{pos:10,name:"Juan Román Riquelme",goals:61},{pos:11,name:"Lionel Messi",goals:58},{pos:12,name:"Marcos Rojo",goals:55},{pos:13,name:"Nicolás Otamendi",goals:52},{pos:14,name:"Paulo Dybala",goals:49},{pos:15,name:"Roberto Ayala",goals:46},{pos:16,name:"Sergio Agüero",goals:43},{pos:17,name:"Walter Samuel",goals:40},{pos:18,name:"Javier Zanetti",goals:37},{pos:19,name:"Esteban Cambiasso",goals:34},{pos:20,name:"Gabriel Batistuta",goals:31}]},
                "D":{teams:[{pos:1,name:"Juniors Club D",pts:31},{pos:2,name:"Progreso Juniors D",pts:29},{pos:3,name:"Unión Juvenil D",pts:27},{pos:4,name:"Los Andes Jr D",pts:25},{pos:5,name:"Atenas Juniors D",pts:23},{pos:6,name:"Belgrano Jr D",pts:21},{pos:7,name:"Racing de Córdoba Jr D",pts:19},{pos:8,name:"Instituto Jr D",pts:17}],scorers:[{pos:1,name:"Alfredo Di Stéfano",goals:91},{pos:2,name:"Bernardo Romeo",goals:88},{pos:3,name:"Claudio Caniggia",goals:85},{pos:4,name:"Daniel Passarella",goals:82},{pos:5,name:"Enrique Wolff",goals:79},{pos:6,name:"Fernando Redondo",goals:76},{pos:7,name:"Jorge Valdano",goals:73},{pos:8,name:"Leopoldo Luque",goals:70},{pos:9,name:"Mario Kempes",goals:67},{pos:10,name:"Norberto Alonso",goals:64},{pos:11,name:"Osvaldo Ardiles",goals:61},{pos:12,name:"Ramón Díaz",goals:58},{pos:13,name:"Silvio Marzolini",goals:55},{pos:14,name:"Ubaldo Fillol",goals:52},{pos:15,name:"Ricardo Bochini",goals:49},{pos:16,name:"José Sanfilippo",goals:46},{pos:17,name:"René Houseman",goals:43},{pos:18,name:"Amadeo Carrizo",goals:40},{pos:19,name:"Antonio Rattín",goals:37},{pos:20,name:"Ángel Labruna",goals:34}]},
                "E1":{teams:[{pos:1,name:"Juniors Club E1",pts:27},{pos:2,name:"Progreso Juniors E1",pts:25},{pos:3,name:"Unión Juvenil E1",pts:23},{pos:4,name:"Los Andes Jr E1",pts:21},{pos:5,name:"Atenas Juniors E1",pts:19},{pos:6,name:"Belgrano Jr E1",pts:17},{pos:7,name:"Racing de Córdoba Jr E1",pts:15},{pos:8,name:"Instituto Jr E1",pts:13}],scorers:[{pos:1,name:"Adolfo Pedernera",goals:87},{pos:2,name:"Carlos Bianchi",goals:84},{pos:3,name:"Diego Maradona",goals:81},{pos:4,name:"Ernesto Grillo",goals:78},{pos:5,name:"Francisco Varallo",goals:75},{pos:6,name:"Guillermo Stábile",goals:72},{pos:7,name:"Herminio Masantonio",goals:69},{pos:8,name:"José Manuel Moreno",goals:66},{pos:9,name:"Luis Artime",goals:63},{pos:10,name:"Manuel Seoane",goals:60},{pos:11,name:"Omar Sívori",goals:57},{pos:12,name:"Raimundo Orsi",goals:54},{pos:13,name:"Roberto Cherro",goals:51},{pos:14,name:"Vicente de la Mata",goals:48},{pos:15,name:"Félix Loustau",goals:45},{pos:16,name:"Juan José Pizzuti",goals:42},{pos:17,name:"Norberto Méndez",goals:39},{pos:18,name:"Orestes Corbatta",goals:36},{pos:19,name:"Rodolfo Orlandini",goals:33},{pos:20,name:"Tucho Méndez",goals:30}]},
                "E2":{teams:[{pos:1,name:"Juniors Club E2",pts:33},{pos:2,name:"Progreso Juniors E2",pts:31},{pos:3,name:"Unión Juvenil E2",pts:29},{pos:4,name:"Los Andes Jr E2",pts:27},{pos:5,name:"Atenas Juniors E2",pts:25},{pos:6,name:"Belgrano Jr E2",pts:23},{pos:7,name:"Racing de Córdoba Jr E2",pts:21},{pos:8,name:"Instituto Jr E2",pts:19}],scorers:[{pos:1,name:"Alberto Márcico",goals:93},{pos:2,name:"Carlos Babington",goals:90},{pos:3,name:"Daniel Bertoni",goals:87},{pos:4,name:"Enzo Francescoli",goals:84},{pos:5,name:"Héctor Yazalde",goals:81},{pos:6,name:"Jorge Burruchaga",goals:78},{pos:7,name:"Juan Sebastián Verón",goals:75},{pos:8,name:"Julio Olarticoechea",goals:72},{pos:9,name:"Nery Pumpido",goals:69},{pos:10,name:"Oscar Ruggeri",goals:66},{pos:11,name:"Ricardo Giusti",goals:63},{pos:12,name:"Roberto Perfumo",goals:60},{pos:13,name:"Sergio Batista",goals:57},{pos:14,name:"Sergio Goycochea",goals:54},{pos:15,name:"Ariel Ortega",goals:51},{pos:16,name:"Claudio López",goals:48},{pos:17,name:"Hernán Díaz",goals:45},{pos:18,name:"Juan Pablo Sorín",goals:42},{pos:19,name:"Kily González",goals:39},{pos:20,name:"Matías Almeyda",goals:36}]}
            },
            "Juveniles": {
                "A":{teams:[{pos:1,name:"Juventud Unida",pts:29},{pos:2,name:"Mitre",pts:27},{pos:3,name:"Nuestra Señora de Luján",pts:26},{pos:4,name:"SAG Lomas",pts:23},{pos:5,name:"Mariano Acosta",pts:20},{pos:6,name:"Ateneo Don Bosco",pts:17},{pos:7,name:"AFALP",pts:13},{pos:8,name:"Lanús",pts:9}],scorers:[{pos:1,name:"Nicolás Barceló García",goals:102},{pos:2,name:"Tobías Ojea Cristino",goals:99},{pos:3,name:"Juan Gull",goals:96},{pos:4,name:"Bautista Gallardo Juv",goals:92},{pos:5,name:"Lorenzo Ortmann",goals:89},{pos:6,name:"Ezequiel Rozitchner",goals:86},{pos:7,name:"Martín Arrom",goals:84},{pos:8,name:"Faustino Belenky",goals:81},{pos:9,name:"Lucas Obregón Gómez",goals:78},{pos:10,name:"Santino Diotallevi",goals:74},{pos:11,name:"Federico Pallero",goals:70},{pos:12,name:"José Khalil Tarazi",goals:67},{pos:13,name:"Juan Montoto",goals:64},{pos:14,name:"Lautaro Rodríguez Juv",goals:61},{pos:15,name:"Santiago Giovanola",goals:58},{pos:16,name:"Tomás Cañete",goals:55},{pos:17,name:"Ramiro Benacedo",goals:52},{pos:18,name:"Pablo Mínguez",goals:49},{pos:19,name:"Juan Saco",goals:46},{pos:20,name:"Tiago Maidana",goals:43}]},
                "B":{teams:[{pos:1,name:"Juventud Unida B",pts:31},{pos:2,name:"Mitre B",pts:28},{pos:3,name:"Nuestra Señora de Luján B",pts:25},{pos:4,name:"SAG Lomas B",pts:22},{pos:5,name:"Mariano Acosta B",pts:19},{pos:6,name:"Ateneo Don Bosco B",pts:16},{pos:7,name:"AFALP B",pts:12},{pos:8,name:"Lanús B",pts:8}],scorers:[{pos:1,name:"Nelson Vivas",goals:101},{pos:2,name:"Pablo Cavallero",goals:98},{pos:3,name:"Roberto Abbondanzieri",goals:95},{pos:4,name:"Rodolfo Arruabarrena",goals:91},{pos:5,name:"Sebastián Battaglia",goals:88},{pos:6,name:"Walter Montillo",goals:85},{pos:7,name:"Clemente Rodríguez",goals:82},{pos:8,name:"Fabián Cubero",goals:79},{pos:9,name:"Germán Lux",goals:76},{pos:10,name:"Hugo Ibarra",goals:73},{pos:11,name:"Leandro Romagnoli",goals:70},{pos:12,name:"Lisandro López",goals:67},{pos:13,name:"Lucho González",goals:64},{pos:14,name:"Martín Demichelis",goals:61},{pos:15,name:"Maxi Rodríguez",goals:58},{pos:16,name:"Nicolás Burdisso",goals:55},{pos:17,name:"Fabricio Coloccini",goals:52},{pos:18,name:"Fernando Cavenaghi",goals:49},{pos:19,name:"Andrés D'Alessandro",goals:46},{pos:20,name:"Carlos Izquierdoz",goals:43}]},
                "C":{teams:[{pos:1,name:"Juventud Unida C",pts:27},{pos:2,name:"Mitre C",pts:25},{pos:3,name:"Nuestra Señora de Luján C",pts:23},{pos:4,name:"SAG Lomas C",pts:21},{pos:5,name:"Mariano Acosta C",pts:18},{pos:6,name:"Ateneo Don Bosco C",pts:15},{pos:7,name:"AFALP C",pts:11},{pos:8,name:"Lanús C",pts:7}],scorers:[{pos:1,name:"Darío Cvitanich",goals:97},{pos:2,name:"Emmanuel Gigliotti",goals:94},{pos:3,name:"Enzo Pérez",goals:91},{pos:4,name:"Ezequiel Lavezzi",goals:88},{pos:5,name:"Facundo Roncaglia",goals:85},{pos:6,name:"Fernando Gago",goals:82},{pos:7,name:"Gabriel Heinze",goals:79},{pos:8,name:"Ignacio Scocco",goals:76},{pos:9,name:"Jonás Gutiérrez",goals:73},{pos:10,name:"Leonardo Ponzio",goals:70},{pos:11,name:"Lucas Biglia",goals:67},{pos:12,name:"Martín Palermo",goals:64},{pos:13,name:"Mauro Zárate",goals:61},{pos:14,name:"Nicolás Gaitán",goals:58},{pos:15,name:"Ricardo Álvarez",goals:55},{pos:16,name:"Rodrigo Palacio",goals:52},{pos:17,name:"Sebastián Domínguez",goals:49},{pos:18,name:"Sergio Romero",goals:46},{pos:19,name:"Willy Caballero",goals:43},{pos:20,name:"Éver Banega",goals:40}]},
                "D":{teams:[{pos:1,name:"Juventud Unida D",pts:30},{pos:2,name:"Mitre D",pts:28},{pos:3,name:"Nuestra Señora de Luján D",pts:26},{pos:4,name:"SAG Lomas D",pts:24},{pos:5,name:"Mariano Acosta D",pts:21},{pos:6,name:"Ateneo Don Bosco D",pts:18},{pos:7,name:"AFALP D",pts:14},{pos:8,name:"Lanús D",pts:10}],scorers:[{pos:1,name:"Augusto Fernández",goals:100},{pos:2,name:"Cristian Ansaldi",goals:97},{pos:3,name:"Erik Lamela",goals:94},{pos:4,name:"Ezequiel Garay",goals:91},{pos:5,name:"Federico Fazio",goals:88},{pos:6,name:"Gabriel Mercado Juv",goals:85},{pos:7,name:"Gerónimo Rulli",goals:82},{pos:8,name:"Guido Pizarro",goals:79},{pos:9,name:"Javier Pastore",goals:76},{pos:10,name:"Leandro Paredes",goals:73},{pos:11,name:"Lucas Ocampos",goals:70},{pos:12,name:"Manuel Lanzini",goals:67},{pos:13,name:"Marcos Acuña",goals:64},{pos:14,name:"Mateo Musacchio",goals:61},{pos:15,name:"Mauro Icardi",goals:58},{pos:16,name:"Nahuel Guzmán",goals:55},{pos:17,name:"Nicolás Pareja",goals:52},{pos:18,name:"Ramiro Funes Mori",goals:49},{pos:19,name:"Roberto Pereyra",goals:46},{pos:20,name:"Ángel Correa",goals:43}]},
                "E1":{teams:[{pos:1,name:"Juventud Unida E1",pts:26},{pos:2,name:"Mitre E1",pts:24},{pos:3,name:"Nuestra Señora de Luján E1",pts:22},{pos:4,name:"SAG Lomas E1",pts:20},{pos:5,name:"Mariano Acosta E1",pts:17},{pos:6,name:"Ateneo Don Bosco E1",pts:14},{pos:7,name:"AFALP E1",pts:10},{pos:8,name:"Lanús E1",pts:6}],scorers:[{pos:1,name:"Cristian Pavón",goals:96},{pos:2,name:"Emanuel Mammana",goals:93},{pos:3,name:"Exequiel Palacios",goals:90},{pos:4,name:"Franco Vázquez",goals:87},{pos:5,name:"Germán Pezzella",goals:84},{pos:6,name:"Giovani Lo Celso",goals:81},{pos:7,name:"Gonzalo Martínez",goals:78},{pos:8,name:"Guido Rodríguez",goals:75},{pos:9,name:"Joaquín Correa",goals:72},{pos:10,name:"Juan Foyth",goals:69},{pos:11,name:"Lautaro Martínez",goals:66},{pos:12,name:"Leonardo Balerdi",goals:63},{pos:13,name:"Lisandro Martínez",goals:60},{pos:14,name:"Lucas Alario",goals:57},{pos:15,name:"Matías Kranevitter",goals:54},{pos:16,name:"Nicolás Tagliafico",goals:51},{pos:17,name:"Paulo Gazzaniga",goals:48},{pos:18,name:"Renzo Saravia",goals:45},{pos:19,name:"Rodrigo De Paul",goals:42},{pos:20,name:"Santiago Ascacíbar",goals:39}]},
                "E2":{teams:[{pos:1,name:"Juventud Unida E2",pts:32},{pos:2,name:"Mitre E2",pts:30},{pos:3,name:"Nuestra Señora de Luján E2",pts:28},{pos:4,name:"SAG Lomas E2",pts:26},{pos:5,name:"Mariano Acosta E2",pts:23},{pos:6,name:"Ateneo Don Bosco E2",pts:20},{pos:7,name:"AFALP E2",pts:16},{pos:8,name:"Lanús E2",pts:12}],scorers:[{pos:1,name:"Adolfo Gaich",goals:102},{pos:2,name:"Agustín Marchesín",goals:99},{pos:3,name:"Alexis Mac Allister",goals:96},{pos:4,name:"Cristian Romero",goals:93},{pos:5,name:"Domingo Blanco",goals:90},{pos:6,name:"Emiliano Buendía",goals:87},{pos:7,name:"Esteban Andrada",goals:84},{pos:8,name:"Facundo Medina",goals:81},{pos:9,name:"Franco Cervi",goals:78},{pos:10,name:"Gonzalo Montiel",goals:75},{pos:11,name:"Julián Álvarez",goals:72},{pos:12,name:"Leonardo Suárez",goals:69},{pos:13,name:"Lucas Martínez Quarta",goals:66},{pos:14,name:"Matías Vargas",goals:63},{pos:15,name:"Nahuel Molina",goals:60},{pos:16,name:"Nehuén Pérez",goals:57},{pos:17,name:"Nicolás Domínguez",goals:54},{pos:18,name:"Rodrigo Battaglia",goals:51},{pos:19,name:"Walter Benítez",goals:48},{pos:20,name:"Emiliano Martínez",goals:45}]}
            },
            "Cadetes": {
                "A":{teams:[{pos:1,name:"Cadetes Ballester",pts:33},{pos:2,name:"Cadetes Ward",pts:31},{pos:3,name:"Cadetes River",pts:28},{pos:4,name:"Cadetes Ferro",pts:26},{pos:5,name:"Cadetes Luján",pts:24},{pos:6,name:"Cadetes Dorrego",pts:22},{pos:7,name:"Cadetes VILO",pts:20},{pos:8,name:"Cadetes Mitre",pts:18}],scorers:[{pos:1,name:"Benjamín Vázquez",goals:105},{pos:2,name:"Bastián Herrera",goals:102},{pos:3,name:"Camilo Soto",goals:99},{pos:4,name:"Dante Rojas",goals:96},{pos:5,name:"Emiliano Castillo",goals:93},{pos:6,name:"Felipe Flores",goals:90},{pos:7,name:"Gael Medina",goals:87},{pos:8,name:"Ignacio Núñez",goals:84},{pos:9,name:"Joaquín Ríos",goals:81},{pos:10,name:"Lorenzo Guzmán",goals:78},{pos:11,name:"Mateo Cabrera",goals:75},{pos:12,name:"Máximo Torres",goals:72},{pos:13,name:"Noah Paredes",goals:69},{pos:14,name:"Santino Domínguez",goals:66},{pos:15,name:"Thiago Otero",goals:63},{pos:16,name:"Valentino Benítez",goals:60},{pos:17,name:"Vito Acosta",goals:57},{pos:18,name:"Bautista Campos",goals:54},{pos:19,name:"Ciro Chávez",goals:51},{pos:20,name:"Dylan Ponce",goals:48}]},
                "B":{teams:[{pos:1,name:"Cadetes Ballester B",pts:35},{pos:2,name:"Cadetes Ward B",pts:32},{pos:3,name:"Cadetes River B",pts:29},{pos:4,name:"Cadetes Ferro B",pts:27},{pos:5,name:"Cadetes Luján B",pts:25},{pos:6,name:"Cadetes Dorrego B",pts:23},{pos:7,name:"Cadetes VILO B",pts:21},{pos:8,name:"Cadetes Mitre B",pts:19}],scorers:[{pos:1,name:"Enzo Fernández",goals:108},{pos:2,name:"Exequiel Zeballos",goals:105},{pos:3,name:"Facundo Buonanotte",goals:102},{pos:4,name:"Fausto Vera",goals:99},{pos:5,name:"Federico Gattoni",goals:96},{pos:6,name:"Francisco Ortega",goals:93},{pos:7,name:"Gastón Ávila",goals:90},{pos:8,name:"Ignacio Miramón",goals:87},{pos:9,name:"Juan Sforza",goals:84},{pos:10,name:"Julián Fernández",goals:81},{pos:11,name:"Kevin Zenón",goals:78},{pos:12,name:"Lautaro Blanco",goals:75},{pos:13,name:"Lucas Beltrán",goals:72},{pos:14,name:"Luis Vázquez",goals:69},{pos:15,name:"Marco Pellegrino",goals:66},{pos:16,name:"Martín Ojeda",goals:63},{pos:17,name:"Matías Palacios",goals:60},{pos:18,name:"Máximo Perrone",goals:57},{pos:19,name:"Nicolás Castro",goals:54},{pos:20,name:"Pablo Solari",goals:51}]},
                "C":{teams:[{pos:1,name:"Cadetes Ballester C",pts:31},{pos:2,name:"Cadetes Ward C",pts:29},{pos:3,name:"Cadetes River C",pts:26},{pos:4,name:"Cadetes Ferro C",pts:24},{pos:5,name:"Cadetes Luján C",pts:22},{pos:6,name:"Cadetes Dorrego C",pts:20},{pos:7,name:"Cadetes VILO C",pts:18},{pos:8,name:"Cadetes Mitre C",pts:16}],scorers:[{pos:1,name:"Pedro de la Vega",goals:101},{pos:2,name:"Ramiro Enrique",goals:98},{pos:3,name:"Santiago Simón",goals:95},{pos:4,name:"Thiago Almada",goals:92},{pos:5,name:"Tomás Pozzo",goals:89},{pos:6,name:"Valentín Barco",goals:86},{pos:7,name:"Valentín Carboni",goals:83},{pos:8,name:"Valentín Gómez",goals:80},{pos:9,name:"Vicente Taborda",goals:77},{pos:10,name:"Alejandro Garnacho",goals:74},{pos:11,name:"Alan Varela",goals:71},{pos:12,name:"Aníbal Moreno",goals:68},{pos:13,name:"Benjamín Domínguez",goals:65},{pos:14,name:"Bruno Amione",goals:62},{pos:15,name:"Carlos Alcaraz",goals:59},{pos:16,name:"Cristian Medina",goals:56},{pos:17,name:"Equi Fernández",goals:53},{pos:18,name:"Ezequiel Bullaude",goals:50},{pos:19,name:"Facundo Farías",goals:47},{pos:20,name:"Gino Infantino",goals:44}]},
                "D":{teams:[{pos:1,name:"Cadetes Ballester D",pts:34},{pos:2,name:"Cadetes Ward D",pts:32},{pos:3,name:"Cadetes River D",pts:29},{pos:4,name:"Cadetes Ferro D",pts:27},{pos:5,name:"Cadetes Luján D",pts:25},{pos:6,name:"Cadetes Dorrego D",pts:23},{pos:7,name:"Cadetes VILO D",pts:21},{pos:8,name:"Cadetes Mitre D",pts:19}],scorers:[{pos:1,name:"Giuliano Simeone",goals:104},{pos:2,name:"Ignacio Maestro Puch",goals:101},{pos:3,name:"Juan Gauto",goals:98},{pos:4,name:"Julián Aude",goals:95},{pos:5,name:"Kevin Lomónaco",goals:92},{pos:6,name:"Lautaro Giaccone",goals:89},{pos:7,name:"Lucas Esquivel",goals:86},{pos:8,name:"Luka Romero",goals:83},{pos:9,name:"Manuel Roffo",goals:80},{pos:10,name:"Marco Di Césare",goals:77},{pos:11,name:"Mateo Retegui",goals:74},{pos:12,name:"Matías Soulé",goals:71},{pos:13,name:"Máximo Kirchner",goals:68},{pos:14,name:"Nahuel Barrios",goals:65},{pos:15,name:"Nicolás Paz",goals:62},{pos:16,name:"Santiago Hezze",goals:59},{pos:17,name:"Tomás Avilés",goals:56},{pos:18,name:"Valentín Castellanos",goals:53},{pos:19,name:"Alex Vigo",goals:50},{pos:20,name:"Brian Aguirre",goals:47}]},
                "E1":{teams:[{pos:1,name:"Cadetes Ballester E1",pts:30},{pos:2,name:"Cadetes Ward E1",pts:28},{pos:3,name:"Cadetes River E1",pts:25},{pos:4,name:"Cadetes Ferro E1",pts:23},{pos:5,name:"Cadetes Luján E1",pts:21},{pos:6,name:"Cadetes Dorrego E1",pts:19},{pos:7,name:"Cadetes VILO E1",pts:17},{pos:8,name:"Cadetes Mitre E1",pts:15}],scorers:[{pos:1,name:"Claudio Echeverri",goals:100},{pos:2,name:"Federico Redondo",goals:97},{pos:3,name:"Gianluca Prestianni",goals:94},{pos:4,name:"Ian Subiabre",goals:91},{pos:5,name:"Jeremías Lázaro",goals:88},{pos:6,name:"Juan Ruberto",goals:85},{pos:7,name:"Kevin Gutiérrez",goals:82},{pos:8,name:"Lucas Román",goals:79},{pos:9,name:"Luciano Gondou",goals:76},{pos:10,name:"Manuel Lanzini Cad",goals:73},{pos:11,name:"Mateo Sanabria",goals:70},{pos:12,name:"Nicolás Fonseca",goals:67},{pos:13,name:"Ramiro Funes Mori Cad",goals:64},{pos:14,name:"Santiago Castro",goals:61},{pos:15,name:"Santiago Montiel",goals:58},{pos:16,name:"Simón DesPuy",goals:55},{pos:17,name:"Tomás Parmo",goals:52},{pos:18,name:"Ulises Sánchez",goals:49},{pos:19,name:"Valentín Barreal",goals:46},{pos:20,name:"Agustín Ruberto",goals:43}]},
                "E2":{teams:[{pos:1,name:"Cadetes Ballester E2",pts:36},{pos:2,name:"Cadetes Ward E2",pts:34},{pos:3,name:"Cadetes River E2",pts:31},{pos:4,name:"Cadetes Ferro E2",pts:29},{pos:5,name:"Cadetes Luján E2",pts:27},{pos:6,name:"Cadetes Dorrego E2",pts:25},{pos:7,name:"Cadetes VILO E2",pts:23},{pos:8,name:"Cadetes Mitre E2",pts:21}],scorers:[{pos:1,name:"Aaron Quirós",goals:106},{pos:2,name:"Abiel Osorio",goals:103},{pos:3,name:"Adrián Martínez",goals:100},{pos:4,name:"Agustín Giay",goals:97},{pos:5,name:"Agustín Palavecino",goals:94},{pos:6,name:"Alan Lescano",goals:91},{pos:7,name:"Baltasar Rodríguez",goals:88},{pos:8,name:"Benjamín Cremaschi",goals:85},{pos:9,name:"Braian Romero",goals:82},{pos:10,name:"Bruno Pittón",goals:79},{pos:11,name:"Damián Pérez",goals:76},{pos:12,name:"David Martínez",goals:73},{pos:13,name:"Diego Valoyes",goals:70},{pos:14,name:"Enzo Díaz",goals:67},{pos:15,name:"Esequiel Barco",goals:64},{pos:16,name:"Facundo Colidio",goals:61},{pos:17,name:"Facundo Tello",goals:58},{pos:18,name:"Felipe Peña Biafore",goals:55},{pos:19,name:"Franco Quinteros",goals:52},{pos:20,name:"Gastón Hernández",goals:49}]}
            },
            "Menores": {
                "A":{teams:[{pos:1,name:"Menores A Team 1",pts:28},{pos:2,name:"Menores A Team 2",pts:26},{pos:3,name:"Menores A Team 3",pts:24},{pos:4,name:"Menores A Team 4",pts:22},{pos:5,name:"Menores A Team 5",pts:20},{pos:6,name:"Menores A Team 6",pts:18},{pos:7,name:"Menores A Team 7",pts:16},{pos:8,name:"Menores A Team 8",pts:14}],scorers:[{pos:1,name:"Menor A Player 1",goals:90},{pos:2,name:"Menor A Player 2",goals:87},{pos:3,name:"Menor A Player 3",goals:84},{pos:4,name:"Menor A Player 4",goals:81},{pos:5,name:"Menor A Player 5",goals:78},{pos:6,name:"Menor A Player 6",goals:75},{pos:7,name:"Menor A Player 7",goals:72},{pos:8,name:"Menor A Player 8",goals:69},{pos:9,name:"Menor A Player 9",goals:66},{pos:10,name:"Menor A Player 10",goals:63},{pos:11,name:"Menor A Player 11",goals:60},{pos:12,name:"Menor A Player 12",goals:57},{pos:13,name:"Menor A Player 13",goals:54},{pos:14,name:"Menor A Player 14",goals:51},{pos:15,name:"Menor A Player 15",goals:48},{pos:16,name:"Menor A Player 16",goals:45},{pos:17,name:"Menor A Player 17",goals:42},{pos:18,name:"Menor A Player 18",goals:39},{pos:19,name:"Menor A Player 19",goals:36},{pos:20,name:"Menor A Player 20",goals:33}]},
                "B":{teams:[{pos:1,name:"Menores B Team 1",pts:30},{pos:2,name:"Menores B Team 2",pts:27},{pos:3,name:"Menores B Team 3",pts:25},{pos:4,name:"Menores B Team 4",pts:23},{pos:5,name:"Menores B Team 5",pts:21},{pos:6,name:"Menores B Team 6",pts:19},{pos:7,name:"Menores B Team 7",pts:17},{pos:8,name:"Menores B Team 8",pts:15}],scorers:[{pos:1,name:"Menor B Player 1",goals:92},{pos:2,name:"Menor B Player 2",goals:89},{pos:3,name:"Menor B Player 3",goals:86},{pos:4,name:"Menor B Player 4",goals:83},{pos:5,name:"Menor B Player 5",goals:80},{pos:6,name:"Menor B Player 6",goals:77},{pos:7,name:"Menor B Player 7",goals:74},{pos:8,name:"Menor B Player 8",goals:71},{pos:9,name:"Menor B Player 9",goals:68},{pos:10,name:"Menor B Player 10",goals:65},{pos:11,name:"Menor B Player 11",goals:62},{pos:12,name:"Menor B Player 12",goals:59},{pos:13,name:"Menor B Player 13",goals:56},{pos:14,name:"Menor B Player 14",goals:53},{pos:15,name:"Menor B Player 15",goals:50},{pos:16,name:"Menor B Player 16",goals:47},{pos:17,name:"Menor B Player 17",goals:44},{pos:18,name:"Menor B Player 18",goals:41},{pos:19,name:"Menor B Player 19",goals:38},{pos:20,name:"Menor B Player 20",goals:35}]},
                "C":{teams:[{pos:1,name:"Menores C Team 1",pts:26},{pos:2,name:"Menores C Team 2",pts:24},{pos:3,name:"Menores C Team 3",pts:22},{pos:4,name:"Menores C Team 4",pts:20},{pos:5,name:"Menores C Team 5",pts:18},{pos:6,name:"Menores C Team 6",pts:16},{pos:7,name:"Menores C Team 7",pts:14},{pos:8,name:"Menores C Team 8",pts:12}],scorers:[{pos:1,name:"Menor C Player 1",goals:88},{pos:2,name:"Menor C Player 2",goals:85},{pos:3,name:"Menor C Player 3",goals:82},{pos:4,name:"Menor C Player 4",goals:79},{pos:5,name:"Menor C Player 5",goals:76},{pos:6,name:"Menor C Player 6",goals:73},{pos:7,name:"Menor C Player 7",goals:70},{pos:8,name:"Menor C Player 8",goals:67},{pos:9,name:"Menor C Player 9",goals:64},{pos:10,name:"Menor C Player 10",goals:61},{pos:11,name:"Menor C Player 11",goals:58},{pos:12,name:"Menor C Player 12",goals:55},{pos:13,name:"Menor C Player 13",goals:52},{pos:14,name:"Menor C Player 14",goals:49},{pos:15,name:"Menor C Player 15",goals:46},{pos:16,name:"Menor C Player 16",goals:43},{pos:17,name:"Menor C Player 17",goals:40},{pos:18,name:"Menor C Player 18",goals:37},{pos:19,name:"Menor C Player 19",goals:34},{pos:20,name:"Menor C Player 20",goals:31}]},
                "D":{teams:[{pos:1,name:"Menores D Team 1",pts:29},{pos:2,name:"Menores D Team 2",pts:27},{pos:3,name:"Menores D Team 3",pts:25},{pos:4,name:"Menores D Team 4",pts:23},{pos:5,name:"Menores D Team 5",pts:21},{pos:6,name:"Menores D Team 6",pts:19},{pos:7,name:"Menores D Team 7",pts:17},{pos:8,name:"Menores D Team 8",pts:15}],scorers:[{pos:1,name:"Menor D Player 1",goals:91},{pos:2,name:"Menor D Player 2",goals:88},{pos:3,name:"Menor D Player 3",goals:85},{pos:4,name:"Menor D Player 4",goals:82},{pos:5,name:"Menor D Player 5",goals:79},{pos:6,name:"Menor D Player 6",goals:76},{pos:7,name:"Menor D Player 7",goals:73},{pos:8,name:"Menor D Player 8",goals:70},{pos:9,name:"Menor D Player 9",goals:67},{pos:10,name:"Menor D Player 10",goals:64},{pos:11,name:"Menor D Player 11",goals:61},{pos:12,name:"Menor D Player 12",goals:58},{pos:13,name:"Menor D Player 13",goals:55},{pos:14,name:"Menor D Player 14",goals:52},{pos:15,name:"Menor D Player 15",goals:49},{pos:16,name:"Menor D Player 16",goals:46},{pos:17,name:"Menor D Player 17",goals:43},{pos:18,name:"Menor D Player 18",goals:40},{pos:19,name:"Menor D Player 19",goals:37},{pos:20,name:"Menor D Player 20",goals:34}]},
                "E1":{teams:[{pos:1,name:"Menores E1 Team 1",pts:25},{pos:2,name:"Menores E1 Team 2",pts:23},{pos:3,name:"Menores E1 Team 3",pts:21},{pos:4,name:"Menores E1 Team 4",pts:19},{pos:5,name:"Menores E1 Team 5",pts:17},{pos:6,name:"Menores E1 Team 6",pts:15},{pos:7,name:"Menores E1 Team 7",pts:13},{pos:8,name:"Menores E1 Team 8",pts:11}],scorers:[{pos:1,name:"Menor E1 Player 1",goals:87},{pos:2,name:"Menor E1 Player 2",goals:84},{pos:3,name:"Menor E1 Player 3",goals:81},{pos:4,name:"Menor E1 Player 4",goals:78},{pos:5,name:"Menor E1 Player 5",goals:75},{pos:6,name:"Menor E1 Player 6",goals:72},{pos:7,name:"Menor E1 Player 7",goals:69},{pos:8,name:"Menor E1 Player 8",goals:66},{pos:9,name:"Menor E1 Player 9",goals:63},{pos:10,name:"Menor E1 Player 10",goals:60},{pos:11,name:"Menor E1 Player 11",goals:57},{pos:12,name:"Menor E1 Player 12",goals:54},{pos:13,name:"Menor E1 Player 13",goals:51},{pos:14,name:"Menor E1 Player 15",goals:48},{pos:15,name:"Menor E1 Player 15",goals:45},{pos:16,name:"Menor E1 Player 16",goals:42},{pos:17,name:"Menor E1 Player 17",goals:39},{pos:18,name:"Menor E1 Player 18",goals:36},{pos:19,name:"Menor E1 Player 19",goals:33},{pos:20,name:"Menor E1 Player 20",goals:30}]},
                "E2":{teams:[{pos:1,name:"Menores E2 Team 1",pts:28},{pos:2,name:"Menores E2 Team 2",pts:26},{pos:3,name:"Menores E2 Team 3",pts:24},{pos:4,name:"Menores E2 Team 4",pts:22},{pos:5,name:"Menores E2 Team 5",pts:20},{pos:6,name:"Menores E2 Team 6",pts:18},{pos:7,name:"Menores E2 Team 7",pts:16},{pos:8,name:"Menores E2 Team 8",pts:14}],scorers:[{pos:1,name:"Menor E2 Player 1",goals:90},{pos:2,name:"Menor E2 Player 2",goals:87},{pos:3,name:"Menor E2 Player 3",goals:84},{pos:4,name:"Menor E2 Player 4",goals:81},{pos:5,name:"Menor E2 Player 5",goals:78},{pos:6,name:"Menor E2 Player 6",goals:75},{pos:7,name:"Menor E2 Player 7",goals:72},{pos:8,name:"Menor E2 Player 8",goals:69},{pos:9,name:"Menor E2 Player 9",goals:66},{pos:10,name:"Menor E2 Player 10",goals:63},{pos:11,name:"Menor E2 Player 11",goals:60},{pos:12,name:"Menor E2 Player 12",goals:57},{pos:13,name:"Menor E2 Player 13",goals:54},{pos:14,name:"Menor E2 Player 14",goals:51},{pos:15,name:"Menor E2 Player 15",goals:48},{pos:16,name:"Menor E2 Player 16",goals:45},{pos:17,name:"Menor E2 Player 17",goals:42},{pos:18,name:"Menor E2 Player 18",goals:39},{pos:19,name:"Menor E2 Player 19",goals:36},{pos:20,name:"Menor E2 Player 20",goals:33}]}
            },
            "Minis": {
                "A":{teams:[{pos:1,name:"Minis A Team 1",pts:25},{pos:2,name:"Minis A Team 2",pts:23},{pos:3,name:"Minis A Team 3",pts:21},{pos:4,name:"Minis A Team 4",pts:20},{pos:5,name:"Minis A Team 5",pts:18},{pos:6,name:"Minis A Team 6",pts:16},{pos:7,name:"Minis A Team 7",pts:14},{pos:8,name:"Minis A Team 8",pts:12}],scorers:[{pos:1,name:"Mini A Player 1",goals:80},{pos:2,name:"Mini A Player 2",goals:77},{pos:3,name:"Mini A Player 3",goals:74},{pos:4,name:"Mini A Player 4",goals:71},{pos:5,name:"Mini A Player 5",goals:68},{pos:6,name:"Mini A Player 6",goals:65},{pos:7,name:"Mini A Player 7",goals:62},{pos:8,name:"Mini A Player 8",goals:59},{pos:9,name:"Mini A Player 9",goals:56},{pos:10,name:"Mini A Player 10",goals:53},{pos:11,name:"Mini A Player 11",goals:50},{pos:12,name:"Mini A Player 12",goals:47},{pos:13,name:"Mini A Player 13",goals:44},{pos:14,name:"Mini A Player 14",goals:41},{pos:15,name:"Mini A Player 15",goals:38},{pos:16,name:"Mini A Player 16",goals:35},{pos:17,name:"Mini A Player 17",goals:32},{pos:18,name:"Mini A Player 18",goals:29},{pos:19,name:"Mini A Player 19",goals:26},{pos:20,name:"Mini A Player 20",goals:23}]},
                "B":{teams:[{pos:1,name:"Minis B Team 1",pts:27},{pos:2,name:"Minis B Team 2",pts:25},{pos:3,name:"Minis B Team 3",pts:23},{pos:4,name:"Minis B Team 4",pts:21},{pos:5,name:"Minis B Team 5",pts:19},{pos:6,name:"Minis B Team 6",pts:17},{pos:7,name:"Minis B Team 7",pts:15},{pos:8,name:"Minis B Team 8",pts:13}],scorers:[{pos:1,name:"Mini B Player 1",goals:82},{pos:2,name:"Mini B Player 2",goals:79},{pos:3,name:"Mini B Player 3",goals:76},{pos:4,name:"Mini B Player 4",goals:73},{pos:5,name:"Mini B Player 5",goals:70},{pos:6,name:"Mini B Player 6",goals:67},{pos:7,name:"Mini B Player 7",goals:64},{pos:8,name:"Mini B Player 8",goals:61},{pos:9,name:"Mini B Player 9",goals:58},{pos:10,name:"Mini B Player 10",goals:55},{pos:11,name:"Mini B Player 11",goals:52},{pos:12,name:"Mini B Player 12",goals:49},{pos:13,name:"Mini B Player 13",goals:46},{pos:14,name:"Mini B Player 14",goals:43},{pos:15,name:"Mini B Player 15",goals:40},{pos:16,name:"Mini B Player 16",goals:37},{pos:17,name:"Mini B Player 17",goals:34},{pos:18,name:"Mini B Player 18",goals:31},{pos:19,name:"Mini B Player 19",goals:28},{pos:20,name:"Mini B Player 20",goals:25}]},
                "C":{teams:[],scorers:[]},"D":{teams:[],scorers:[]},"E1":{teams:[],scorers:[]},"E2":{teams:[],scorers:[]}
            }
        },
        "Femenino": {
            "Mayores": {
                "A":{teams:[{pos:1,name:"CI.DE.CO.",pts:45},{pos:2,name:"Club Atlético Vélez Sarsfield",pts:41},{pos:3,name:"Ferro Carril Oeste (F)",pts:38},{pos:4,name:"River Plate (F)",pts:36},{pos:5,name:"Estudiantes LP (F)",pts:32},{pos:6,name:"Municipalidad de Vicente López",pts:29},{pos:7,name:"Lanús (F)",pts:26},{pos:8,name:"Regatas de Mendoza",pts:21}],scorers:[{pos:1,name:"Elke Karsten",goals:130},{pos:2,name:"Luciana Mendoza",goals:125},{pos:3,name:"Macarena Sans",goals:121},{pos:4,name:"Malena Cavo",goals:117},{pos:5,name:"Micaela Casasola",goals:113},{pos:6,name:"Ayelén García",goals:109},{pos:7,name:"Giuliana Gavilán",goals:105},{pos:8,name:"Rocío Campigli",goals:101},{pos:9,name:"Manuela Pizzo",goals:97},{pos:10,name:"Macarena Gandulfo",goals:93},{pos:11,name:"Marisol Carratú",goals:89},{pos:12,name:"Leila Niño",goals:85},{pos:13,name:"Rosario Urban",goals:81},{pos:14,name:"Martina Romero",goals:77},{pos:15,name:"Carolina Bono",goals:73},{pos:16,name:"Delfina Ojea",goals:69},{pos:17,name:"Lucía Dalle",goals:65},{pos:18,name:"Ayelén Rosalez",goals:61},{pos:19,name:"Sofía Rivadeneira",goals:57},{pos:20,name:"Valentina Brodsky",goals:53}]},
                "B":{teams:[{pos:1,name:"CI.DE.CO. B",pts:47},{pos:2,name:"Vélez Sarsfield B",pts:43},{pos:3,name:"Ferro (F) B",pts:40},{pos:4,name:"River (F) B",pts:38},{pos:5,name:"Estudiantes (F) B",pts:34},{pos:6,name:"Muni Vicente López B",pts:31},{pos:7,name:"Lanús (F) B",pts:28},{pos:8,name:"Regatas Mendoza B",pts:23}],scorers:[{pos:1,name:"Aldana Cassan",goals:132},{pos:2,name:"Berenice Frelier",goals:127},{pos:3,name:"Carla Rebecchi",goals:123},{pos:4,name:"Delfina Merino",goals:119},{pos:5,name:"Eugenia Trinchinetti",goals:115},{pos:6,name:"Florencia Habif",goals:111},{pos:7,name:"Giselle Kañevsky",goals:107},{pos:8,name:"Inés Arrondo",goals:103},{pos:9,name:"Jorgelina Bertoni",goals:99},{pos:10,name:"Karina Masotta",goals:95},{pos:11,name:"Luciana Aymar",goals:91},{pos:12,name:"Magdalena Aicega",goals:87},{pos:13,name:"Mariela Scarone",goals:83},{pos:14,name:"Noel Barrionuevo",goals:79},{pos:15,name:"Pilar Campoy",goals:75},{pos:16,name:"Rocío Sánchez Moccia",goals:71},{pos:17,name:"Silvina D'Elía",goals:67},{pos:18,name:"Soledad García",goals:63},{pos:19,name:"Vanina Oneto",goals:59},{pos:20,name:"Victoria Zuloaga",goals:55}]},
                "C":{teams:[{pos:1,name:"CI.DE.CO. C",pts:43},{pos:2,name:"Vélez Sarsfield C",pts:39},{pos:3,name:"Ferro (F) C",pts:36},{pos:4,name:"River (F) C",pts:34},{pos:5,name:"Estudiantes (F) C",pts:30},{pos:6,name:"Muni Vicente López C",pts:27},{pos:7,name:"Lanús (F) C",pts:24},{pos:8,name:"Regatas Mendoza C",pts:19}],scorers:[{pos:1,name:"Agustina Albertario",goals:128},{pos:2,name:"Belén Succi",goals:123},{pos:3,name:"Candela Otero",goals:119},{pos:4,name:"Daniela Sruoga",goals:115},{pos:5,name:"Estefanía Cascallares",goals:111},{pos:6,name:"Florencia Mutio",goals:107},{pos:7,name:"Gabriela Pando",goals:103},{pos:8,name:"Julieta Jankunas",goals:99},{pos:9,name:"Laura Aladro",goals:95},{pos:10,name:"Macarena Rodríguez",goals:91},{pos:11,name:"María José Granatto",goals:87},{pos:12,name:"Micaela Retegui",goals:83},{pos:13,name:"Natalia Del Prete",goals:79},{pos:14,name:"Paola Vukojicic",goals:75},{pos:15,name:"Pilar Romang",goals:71},{pos:16,name:"Rosario Luchetti",goals:67},{pos:17,name:"Sofía Maccari",goals:63},{pos:18,name:"Valentina Raposo",goals:59},{pos:19,name:"Victoria Granatto",goals:55},{pos:20,name:"Agostina Alonso",goals:51}]},
                "D":{teams:[{pos:1,name:"CI.DE.CO. D",pts:46},{pos:2,name:"Vélez Sarsfield D",pts:42},{pos:3,name:"Ferro (F) D",pts:39},{pos:4,name:"River (F) D",pts:37},{pos:5,name:"Estudiantes (F) D",pts:33},{pos:6,name:"Muni Vicente López D",pts:30},{pos:7,name:"Lanús (F) D",pts:27},{pos:8,name:"Regatas Mendoza D",pts:22}],scorers:[{pos:1,name:"Agustina Gorzelany",goals:131},{pos:2,name:"Bárbara Dichiara",goals:126},{pos:3,name:"Carla Dupuy",goals:122},{pos:4,name:"Constanza Cerundolo",goals:118},{pos:5,name:"Emilia Forcherio",goals:114},{pos:6,name:"Guadalupe Adorno",goals:110},{pos:7,name:"Juana Castellaro",goals:106},{pos:8,name:"Lara Casas",goals:102},{pos:9,name:"Martina Triñanes",goals:98},{pos:10,name:"Pilar De Biase",goals:94},{pos:11,name:"Sofía Cairo",goals:90},{pos:12,name:"Valentina Marcucci",goals:86},{pos:13,name:"Zoe Díaz",goals:82},{pos:14,name:"Alejandra Gulla",goals:78},{pos:15,name:"Anabel Gambero",goals:74},{pos:16,name:"Ayelén Stepnik",goals:70},{pos:17,name:"Cecilia Rognoni",goals:66},{pos:18,name:"Claudia Burkart",goals:62},{pos:19,name:"Giselle Kanevsky",goals:58},{pos:20,name:"Mariné Russo",goals:54}]},
                "E1":{teams:[{pos:1,name:"CI.DE.CO. E1",pts:42},{pos:2,name:"Vélez Sarsfield E1",pts:38},{pos:3,name:"Ferro (F) E1",pts:35},{pos:4,name:"River (F) E1",pts:33},{pos:5,name:"Estudiantes (F) E1",pts:29},{pos:6,name:"Muni Vicente López E1",pts:26},{pos:7,name:"Lanús (F) E1",pts:23},{pos:8,name:"Regatas Mendoza E1",pts:18}],scorers:[{pos:1,name:"Mercedes Margalot",goals:127},{pos:2,name:"Mercedes Paz",goals:122},{pos:3,name:"Mónica Fierro",goals:118},{pos:4,name:"Paola Suárez",goals:114},{pos:5,name:"Raquel Ripoll",goals:110},{pos:6,name:"Romina Vatteone",goals:106},{pos:7,name:"Vanina Pardo",goals:102},{pos:8,name:"Verónica Alfonso",goals:98},{pos:9,name:"Virginia De Biase",goals:94},{pos:10,name:"Ximena Camadro",goals:90},{pos:11,name:"Yésica Arrupe",goals:86},{pos:12,name:"Sofía Vercelli",goals:82},{pos:13,name:"Sabrina Molina",goals:78},{pos:14,name:"Natalia Cattáneo",goals:74},{pos:15,name:"Laura Maiztegui",goals:70},{pos:16,name:"Josefina Sruoga",goals:66},{pos:17,name:"Julia Gómes Fantasia",goals:62},{pos:18,name:"Florencia D'Elía",goals:58},{pos:19,name:"Daniela Maloberti",goals:54},{pos:20,name:"Cecilia Del Carril",goals:50}]},
                "E2":{teams:[{pos:1,name:"CI.DE.CO. E2",pts:48},{pos:2,name:"Vélez Sarsfield E2",pts:44},{pos:3,name:"Ferro (F) E2",pts:41},{pos:4,name:"River (F) E2",pts:39},{pos:5,name:"Estudiantes (F) E2",pts:35},{pos:6,name:"Muni Vicente López E2",pts:32},{pos:7,name:"Lanús (F) E2",pts:29},{pos:8,name:"Regatas Mendoza E2",pts:24}],scorers:[{pos:1,name:"Ana Paula De la Torre",goals:133},{pos:2,name:"Brisa Bruggesser",goals:128},{pos:3,name:"Catalina Andrade",goals:124},{pos:4,name:"Celina Di Santo",goals:120},{pos:5,name:"Clara Barberi",goals:116},{pos:6,name:"Daiana Pacheco",goals:112},{pos:7,name:"Francisca Concetti",goals:108},{pos:8,name:"Ivana Raptis",goals:104},{pos:9,name:"Josefina Ruben",goals:100},{pos:10,name:"Lourdes Pérez",goals:96},{pos:11,name:"Malena Sabez",goals:92},{pos:12,name:"Mariana Scandura",goals:88},{pos:13,name:"Mili Cascallares",goals:84},{pos:14,name:"Sol Pagella",goals:80},{pos:15,name:"Valentina Ferola",goals:76},{pos:16,name:"Victoria Miranda",goals:72},{pos:17,name:"Yazmín Pallot",goals:68},{pos:18,name:"Micaela Siri",goals:64},{pos:19,name:"Justina Paz",goals:60},{pos:20,name:"Bianca Donati",goals:56}]}
            },
            "Juniors": {
                "A":{teams:[{pos:1,name:"Juniors Fem A Team 1",pts:30},{pos:2,name:"Juniors Fem A Team 2",pts:28},{pos:3,name:"Juniors Fem A Team 3",pts:25},{pos:4,name:"Juniors Fem A Team 4",pts:22},{pos:5,name:"Juniors Fem A Team 5",pts:19},{pos:6,name:"Juniors Fem A Team 6",pts:15},{pos:7,name:"Juniors Fem A Team 7",pts:12},{pos:8,name:"Juniors Fem A Team 8",pts:10}],scorers:[{pos:1,name:"Ana Pérez",goals:95},{pos:2,name:"Beatriz Gómez",goals:91},{pos:3,name:"Carla Ruiz",goals:88},{pos:4,name:"Diana Torres",goals:85},{pos:5,name:"Elena Castro",goals:82},{pos:6,name:"Fátima Moreno",goals:79},{pos:7,name:"Gloria Navarro",goals:75},{pos:8,name:"Inés Romero",goals:71},{pos:9,name:"Juana Vargas",goals:68},{pos:10,name:"Laura Díaz",goals:65},{pos:11,name:"Marta Herrera",goals:62},{pos:12,name:"Nerea Alonso",goals:59},{pos:13,name:"Olga Mendoza",goals:56},{pos:14,name:"Pilar Castillo",goals:53},{pos:15,name:"Raquel Ortega",goals:50},{pos:16,name:"Sara Núñez",goals:47},{pos:17,name:"Teresa Medina",goals:44},{pos:18,name:"Úrsula Ríos",goals:41},{pos:19,name:"Verónica Flores",goals:38},{pos:20,name:"Ximena Guzmán",goals:35}]},
                "B":{teams:[{pos:1,name:"Juniors Fem B Team 1",pts:32},{pos:2,name:"Juniors Fem B Team 2",pts:29},{pos:3,name:"Juniors Fem B Team 3",pts:26},{pos:4,name:"Juniors Fem B Team 4",pts:24},{pos:5,name:"Juniors Fem B Team 5",pts:21},{pos:6,name:"Juniors Fem B Team 6",pts:18},{pos:7,name:"Juniors Fem B Team 7",pts:14},{pos:8,name:"Juniors Fem B Team 8",pts:11}],scorers:[{pos:1,name:"Alicia Vega",goals:98},{pos:2,name:"Bárbara Salas",goals:94},{pos:3,name:"Cristina Bravo",goals:90},{pos:4,name:"Dolores Guerrero",goals:87},{pos:5,name:"Ester Ramos",goals:83},{pos:6,name:"Flavia Figueroa",goals:80},{pos:7,name:"Gema Salazar",goals:76},{pos:8,name:"Irene Cuesta",goals:72},{pos:9,name:"Lidia Montes",goals:69},{pos:10,name:"Manuela Bravo",goals:66},{pos:11,name:"Mercedes Guerrero",goals:63},{pos:12,name:"Noelia Ramos",goals:60},{pos:13,name:"Patricia Figueroa",goals:57},{pos:14,name:"Rebeca Salazar",goals:54},{pos:15,name:"Rosa Cuesta",goals:51},{pos:16,name:"Silvia Montes",goals:48},{pos:17,name:"Susana Bravo",goals:45},{pos:18,name:"Tamara Guerrero",goals:42},{pos:19,name:"Yolanda Ramos",goals:39},{pos:20,name:"Zaira Figueroa",goals:36}]},
                "C":{teams:[],scorers:[]},"D":{teams:[],scorers:[]},"E1":{teams:[],scorers:[]},"E2":{teams:[],scorers:[]}
            },
            "Juveniles": {
                "A":{teams:[{pos:1,name:"Juv. Fem A Team 1",pts:29},{pos:2,name:"Juv. Fem A Team 2",pts:27},{pos:3,name:"Juv. Fem A Team 3",pts:26},{pos:4,name:"Juv. Fem A Team 4",pts:23},{pos:5,name:"Juv. Fem A Team 5",pts:20},{pos:6,name:"Juv. Fem A Team 6",pts:17},{pos:7,name:"Juv. Fem A Team 7",pts:13},{pos:8,name:"Juv. Fem A Team 8",pts:9}],scorers:[{pos:1,name:"Ada Soler",goals:102},{pos:2,name:"Berta Vidal",goals:99},{pos:3,name:"Celia Vega",goals:96},{pos:4,name:"Dora Salas",goals:92},{pos:5,name:"Elisa Bravo",goals:89},{pos:6,name:"Felisa Guerrero",goals:86},{pos:7,name:"Gala Ramos",goals:84},{pos:8,name:"Hebe Figueroa",goals:81},{pos:9,name:"Iria Salazar",goals:78},{pos:10,name:"Jimena Cuesta",goals:74},{pos:11,name:"Lara Montes",goals:70},{pos:12,name:"Mar Bravo",goals:67},{pos:13,name:"Nora Guerrero",goals:64},{pos:14,name:"Olivia Ramos",goals:61},{pos:15,name:"Paula Figueroa",goals:58},{pos:16,name:"Rita Salazar",goals:55},{pos:17,name:"Sira Cuesta",goals:52},{pos:18,name:"Tania Montes",goals:49},{pos:19,name:"Valeria Bravo",goals:46},{pos:20,name:"Zoe Guerrero",goals:43}]},
                "B":{teams:[{pos:1,name:"Barrio Parque",pts:43},{pos:2,name:"Jockey Club Córdoba",pts:40},{pos:3,name:"Godoy Cruz Antonio Tomba",pts:37},{pos:4,name:"Universidad Nacional de Cuyo",pts:35},{pos:5,name:"Club Alemán de Quilmes",pts:31},{pos:6,name:"Instituto Sagrado Corazón",pts:28},{pos:7,name:"Club Yupanqui",pts:25},{pos:8,name:"Nueva Generación Alberdi",pts:22}],scorers:[{pos:1,name:"Agustina Mirotta",goals:128},{pos:2,name:"Alma Jazmín Molina",goals:124},{pos:3,name:"Fiorella Corimberto",goals:120},{pos:4,name:"Gisella Bonomi",goals:116},{pos:5,name:"Lucila Candela Balsas",goals:112},{pos:6,name:"Zoe Turnes",goals:108},{pos:7,name:"Camila Pedernera",goals:104},{pos:8,name:"Joana Bolling",goals:100},{pos:9,name:"Victoria Crivelli",goals:96},{pos:10,name:"Antonela Mena",goals:92},{pos:11,name:"Xoana Iacoi",goals:68},{pos:12,name:"Valentina Kogan",goals:84},{pos:13,name:"Bibiana Ferrea",goals:80},{pos:14,name:"Camila Bonazzola",goals:76},{pos:15,name:"Nadia Bordón",goals:72},{pos:16,name:"Natalia Vico",goals:68},{pos:17,name:"Silvana Totolo",goals:64},{pos:18,name:"Luciana Scordamaglia",goals:60},{pos:19,name:"Florencia Bericio",goals:56},{pos:20,name:"Amelia Belotti",goals:52}]},
                "C":{teams:[],scorers:[]},"D":{teams:[],scorers:[]},"E1":{teams:[],scorers:[]},"E2":{teams:[],scorers:[]}
            },
            "Cadetes": {
                "A":{teams:[{pos:1,name:"Muni. de Maipú",pts:38},{pos:2,name:"Luján de Cuyo",pts:36},{pos:3,name:"Andes Talleres",pts:34},{pos:4,name:"Gimnasia y Esgrima (Mza)",pts:32},{pos:5,name:"Independiente Rivadavia",pts:30},{pos:6,name:"San Martín (Mza)",pts:28},{pos:7,name:"Huracán Las Heras",pts:26},{pos:8,name:"Palmira",pts:24}],scorers:[{pos:1,name:"Abril Acosta",goals:115},{pos:2,name:"Bianca Fernández",goals:112},{pos:3,name:"Clara Giménez",goals:109},{pos:4,name:"Delfina Morales",goals:106},{pos:5,name:"Emma Navarro",goals:103},{pos:6,name:"Florencia Peralta",goals:100},{pos:7,name:"Guadalupe Ríos",goals:97},{pos:8,name:"Helena Soto",goals:94},{pos:9,name:"Isabella Vargas",goals:91},{pos:10,name:"Jazmín Castro",goals:88},{pos:11,name:"Lola Herrera",goals:85},{pos:12,name:"Martina Domínguez",goals:82},{pos:13,name:"Mía Paredes",goals:79},{pos:14,name:"Nina Rivas",goals:76},{pos:15,name:"Olivia Cruz",goals:73},{pos:16,name:"Paz Campos",goals:70},{pos:17,name:"Renata Chávez",goals:67},{pos:18,name:"Sara Ponce",goals:64},{pos:19,name:"Tiziana Ferreyra",goals:61},{pos:20,name:"Zoe Ayala",goals:58}]},
                "B":{teams:[{pos:1,name:"Muni. de Maipú B",pts:40},{pos:2,name:"Luján de Cuyo B",pts:38},{pos:3,name:"Andes Talleres B",pts:36},{pos:4,name:"Gimnasia (Mza) B",pts:34},{pos:5,name:"Indep. Rivadavia B",pts:32},{pos:6,name:"San Martín (Mza) B",pts:30},{pos:7,name:"Huracán LH B",pts:28},{pos:8,name:"Palmira B",pts:26}],scorers:[{pos:1,name:"Alma Rojas",goals:118},{pos:2,name:"Brisa Torres",goals:115},{pos:3,name:"Catalina Cabrera",goals:112},{pos:4,name:"Dana Paredes",goals:109},{pos:5,name:"Esmeralda Domínguez",goals:106},{pos:6,name:"Frida Otero",goals:103},{pos:7,name:"Greta Benítez",goals:100},{pos:8,name:"India Acosta",goals:97},{pos:9,name:"Jade Campos",goals:94},{pos:10,name:"Kiara Chávez",goals:91},{pos:11,name:"Luz Ponce",goals:88},{pos:12,name:"Malena Ferreyra",goals:85},{pos:13,name:"Morena Ayala",goals:82},{pos:14,name:"Nahiara Rojas",goals:79},{pos:15,name:"Perla Torres",goals:76},{pos:16,name:"Regina Cabrera",goals:73},{pos:17,name:"Roma Paredes",goals:70},{pos:18,name:"Sabrina Domínguez",goals:67},{pos:19,name:"Uma Otero",goals:64},{pos:20,name:"Wanda Benítez",goals:61}]},
                "C":{teams:[],scorers:[]},"D":{teams:[],scorers:[]},"E1":{teams:[],scorers:[]},"E2":{teams:[],scorers:[]}
            },
            "Menores": {
                "A":{teams:[{pos:1,name:"Menores Fem A Team 1",pts:28},{pos:2,name:"Menores Fem A Team 2",pts:26},{pos:3,name:"Menores Fem A Team 3",pts:24},{pos:4,name:"Menores Fem A Team 4",pts:22},{pos:5,name:"Menores Fem A Team 5",pts:20},{pos:6,name:"Menores Fem A Team 6",pts:18},{pos:7,name:"Menores Fem A Team 7",pts:16},{pos:8,name:"Menores Fem A Team 8",pts:14}],scorers:[{pos:1,name:"Menor Fem A Player 1",goals:90},{pos:2,name:"Menor Fem A Player 2",goals:87},{pos:3,name:"Menor Fem A Player 3",goals:84},{pos:4,name:"Menor Fem A Player 4",goals:81},{pos:5,name:"Menor Fem A Player 5",goals:78},{pos:6,name:"Menor Fem A Player 6",goals:75},{pos:7,name:"Menor Fem A Player 7",goals:72},{pos:8,name:"Menor Fem A Player 8",goals:69},{pos:9,name:"Menor Fem A Player 9",goals:66},{pos:10,name:"Menor Fem A Player 10",goals:63},{pos:11,name:"Menor Fem A Player 11",goals:60},{pos:12,name:"Menor Fem A Player 12",goals:57},{pos:13,name:"Menor Fem A Player 13",goals:54},{pos:14,name:"Menor Fem A Player 14",goals:51},{pos:15,name:"Menor Fem A Player 15",goals:48},{pos:16,name:"Menor Fem A Player 16",goals:45},{pos:17,name:"Menor Fem A Player 17",goals:42},{pos:18,name:"Menor Fem A Player 18",goals:39},{pos:19,name:"Menor Fem A Player 19",goals:36},{pos:20,name:"Menor Fem A Player 20",goals:33}]},
                "B":{teams:[],scorers:[]},"C":{teams:[],scorers:[]},"D":{teams:[],scorers:[]},"E1":{teams:[],scorers:[]},"E2":{teams:[],scorers:[]}
            },
            "Minis": {
                "A":{teams:[{pos:1,name:"Minis Fem A Team 1",pts:25},{pos:2,name:"Minis Fem A Team 2",pts:23},{pos:3,name:"Minis Fem A Team 3",pts:21},{pos:4,name:"Minis Fem A Team 4",pts:20},{pos:5,name:"Minis Fem A Team 5",pts:18},{pos:6,name:"Minis Fem A Team 6",pts:16},{pos:7,name:"Minis Fem A Team 7",pts:14},{pos:8,name:"Minis Fem A Team 8",pts:12}],scorers:[{pos:1,name:"Mini Fem A Player 1",goals:80},{pos:2,name:"Mini Fem A Player 2",goals:77},{pos:3,name:"Mini Fem A Player 3",goals:74},{pos:4,name:"Mini Fem A Player 4",goals:71},{pos:5,name:"Mini Fem A Player 5",goals:68},{pos:6,name:"Mini Fem A Player 6",goals:65},{pos:7,name:"Mini Fem A Player 7",goals:62},{pos:8,name:"Mini Fem A Player 8",goals:59},{pos:9,name:"Mini Fem A Player 9",goals:56},{pos:10,name:"Mini Fem A Player 10",goals:53},{pos:11,name:"Mini Fem A Player 11",goals:50},{pos:12,name:"Mini Fem A Player 12",goals:47},{pos:13,name:"Mini Fem A Player 13",goals:44},{pos:14,name:"Mini Fem A Player 14",goals:41},{pos:15,name:"Mini Fem A Player 15",goals:38},{pos:16,name:"Mini Fem A Player 16",goals:35},{pos:17,name:"Mini Fem A Player 17",goals:32},{pos:18,name:"Mini Fem A Player 18",goals:29},{pos:19,name:"Mini Fem A Player 19",goals:26},{pos:20,name:"Mini Fem A Player 20",goals:23}]},
                "B":{teams:[],scorers:[]},"C":{teams:[],scorers:[]},"D":{teams:[],scorers:[]},"E1":{teams:[],scorers:[]},"E2":{teams:[],scorers:[]}
            }
        }
    };

    const userSelection = { branch: null, category: null, division: null };
    const categoryTitle = document.getElementById('category-title');
    const divisionTitle = document.getElementById('division-title');
    const tablesBreadcrumb = document.getElementById('tables-breadcrumb');
    const teamsTableBody = document.getElementById('teams-table-body');
    const scorersTableBody = document.getElementById('scorers-table-body');

    function switchScreen(targetId) {
        document.querySelectorAll('.screen').forEach(screen => screen.classList.remove('active'));
        const targetScreen = document.getElementById(targetId);
        if (targetScreen) targetScreen.classList.add('active');
    }

    function updateTables(branch, category, division) {
        teamsTableBody.innerHTML = '';
        scorersTableBody.innerHTML = '';
        const data = tableData[branch]?.[category]?.[division];
        if (data && data.teams.length > 0) {
            data.teams.forEach(team => {
                teamsTableBody.innerHTML += `<tr><td>${team.pos}</td><td>${team.name}</td><td>${team.pts}</td></tr>`;
            });
            data.scorers.forEach(scorer => {
                scorersTableBody.innerHTML += `<tr><td>${scorer.pos}</td><td>${scorer.name}</td><td>${scorer.goals}</td></tr>`;
            });
        } else {
            const noDataMessage = '<td colspan="3">No hay datos para esta selección.</td>';
            teamsTableBody.innerHTML = `<tr>${noDataMessage}</tr>`;
            scorersTableBody.innerHTML = `<tr>${noDataMessage}</tr>`;
        }
    }

    document.body.addEventListener('click', (event) => {
        const target = event.target;
        if (target.matches('.nav-button, .back-button')) {
            const targetScreenId = target.dataset.target;
            const value = target.dataset.value;
            if (targetScreenId === 'screen-category') {
                userSelection.branch = value;
                categoryTitle.textContent = userSelection.branch;
            } else if (targetScreenId === 'screen-division') {
                userSelection.category = value;
                divisionTitle.textContent = `${userSelection.branch} - ${userSelection.category}`;
            } else if (targetScreenId === 'screen-tables') {
                userSelection.division = value;
                tablesBreadcrumb.textContent = `Rama ${userSelection.branch} / ${userSelection.category} / División ${userSelection.division}`;
                updateTables(userSelection.branch, userSelection.category, userSelection.division);
            }
            if (target.id === 'reset-selection') {
                userSelection.branch = null; userSelection.category = null; userSelection.division = null;
            }
            switchScreen(targetScreenId);
        }
    });
});
